class Urls:
    BASE_URL = 'https://qa-scooter.praktikum-services.ru'
    CREATE_COURIER_URL = BASE_URL + '/api/v1/courier'
    LOGIN_COURIER_URL = BASE_URL + '/api/v1/courier/login'
    CREATE_ORDER_URL = BASE_URL + '/api/v1/orders'
    GET_ORDERS_LIST = BASE_URL + '/api/v1/orders'
    DELETE_COURIER_URL = BASE_URL + '/api/v1/courier/{courier_id}'
    ACCEPT_ORDER_URL = BASE_URL + '/api/v1/orders/accept/{order_id}?courierId={courier_id}'
    GET_ORDER_BY_TRACK_URL = BASE_URL + '/api/v1/orders/track?t={track}'
    FINISH_ORDER_URL = BASE_URL + '/api/v1/orders/finish/{order_id}'
